
&НаСервере
Функция ВыполнитьРасчетНаСервере()
	
	//"AQGQAgAAAAAAAO+7v3siIyIsYWNmNjE5MmUtODFjYS00NmVmLTkzYTYtNWE2OTY4Yjc4NjYzLA0KezksDQp7NSwNCnswLCJMaW5lTnVtYmVyIiwNCnsiUGF0dGVybiIsDQp7Ik4iLDUsMCwxfQ0KfSwiIiwyMH0sDQp7MSwi0JzQuNC90JPRgNCw0L3QuNGG0LAiLA0KeyJQYXR0ZXJuIiwNCnsiTiIsMTgsMiwxfQ0KfSwiIiwyMH0sDQp7Miwi0JzQsNC60YHQk9GA0LDQvdC40YbQsCIsDQp7IlBhdHRlcm4iLA0KeyJOIiwxOCwyLDF9DQp9LCIiLDIwfSwNCnszLCLQmtC+0Y3RhNGE0LjRhtC40LXQvdGCIiwNCnsiUGF0dGVybiIsDQp7Ik4iLDcsNCwxfQ0KfSwiIiwyMH0sDQp7NCwiU291cmNlTGluZU51bWJlciIsDQp7IlBhdHRlcm4iLA0KeyJOIn0NCn0sIiIsMjB9DQp9LA0KezIsNSwwLDAsMSwxLDIsMiwzLDMsNCw0LA0KezEsMywNCnsyLDAsNSwNCnsiTiIsMX0sDQp7Ik4iLDB9LA0KeyJOIiwyNTAwMDB9LA0KeyJOIiwwLjA2fSwNCnsiTiIsMH0sMH0sDQp7MiwxLDUsDQp7Ik4iLDJ9LA0KeyJOIiwyNTAwMDB9LA0KeyJOIiw1MDAwMDB9LA0KeyJOIiwwLjA1MjV9LA0KeyJOIiwwfSwwfSwNCnsyLDIsNSwNCnsiTiIsM30sDQp7Ik4iLDUwMDAwMH0sDQp7Ik4iLDk5OTk5OTk5OTk5OTk5OTl9LA0KeyJOIiwwLjA1fSwNCnsiTiIsMH0sMH0NCn0sNCwyfSwNCnswLDB9DQp9DQp9"
	ЭтаОбработка = РеквизитФормыВЗначение("Объект");
	СтруктураПараметров = Новый Структура;
	СтруктураПараметров.Вставить("ДоговорДУ", ДоговорДУ);
	СтруктураПараметров.Вставить("Дата",Дата);
	
	ПользовательскиеНастройки = ДоговорКонтрагента.НастройкиАлгоритма2.Получить();
	СтруктураОтвета = ЭтаОбработка.РезультатРасчета(ПользовательскиеНастройки, СтруктураПараметров);
	Ответ = СтруктураОтвета.СправкаРасчет.Получить();

	ТабДок = Новый ТабличныйДокумент;
	ТабДок.Вывести(Ответ.ШапкаРасчет); 
	ТабДок.Вывести(Ответ.ТелоРасчет); 
	ТабДок.Вывести(Ответ.ПодвалРасчет);
	Возврат ТабДок;
КонецФункции

&НаКлиенте
Процедура ВыполнитьРасчет(Команда)
	ТабДок = ВыполнитьРасчетНаСервере();
	ТабДок.Показать();
КонецПроцедуры
